version: '3.8'
services:
  database:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5431:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env # 2do: not really necessary since path defaults to (.env), left for clarity, remove later
volumes:
  database:
    driver: local